name: CSS Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
        name: Set up Node.js

      - name: Install stylelint
        run: npm install stylelint --save-dev

      - name: Run stylelint
        run: npx stylelint "**/*.css"
